### ISSUE TITLE
some of my doubts

### ISSUE THREAD

**Issue by XYXhong** [ecolab-nus/lisa#3]
First, let me talk about my experimental example. I run cholesky, its II is 1, and the cgra structure is arch-homo-orth_4_4.xml. I have the following doubts:
1. I found that some operators in the result are placed in the same PE, including the load operator and sub operator,and even there is no edge between these two operators. Why can this be achieved?
2. I found that the final mapping position of two operators contained in some edges is not adjacent, but across a grid or diagonal. How is this routed? After all, I am using arch-homo-orth_4_4.xml, which should not support crossing a grid or diagonal.

**Comment by zhaoying-LI** [comment]
Thanks for your interest. In my opinion, I think both two cases are valid. Could you use the internal print command to check the mapping(you need to set the environment variable to enable printing), or can you send me some logs so I can check further? For the first question, the short answer is that one PE has multiple function units so that the PE can execute multiple operations in parallel.

**Comment by XYXhong** [comment]
There are information about the instance I run in the attachment. How is the route from Mul0 to Load2 and Load3 realized?
![qq_pic_merged_1680675106664](https://user-images.githubusercontent.com/103161700/231183325-85bf4794-0cba-480c-bc44-b991683908dd.jpg)
![V3%@6S4_LQ2F%Q {LDSDY}9](https://user-images.githubusercontent.com/103161700/231183336-a018a204-22fa-4e4c-b236-a2e48cdf958e.png)
![YYV0B46 @GBM6E131 E3`9C](https://user-images.githubusercontent.com/103161700/231183342-b3a422e0-92ca-4a83-8e5f-a8a1509aef57.png)

**Comment by zhaoying-LI** [comment]
Emm, you can dump the routing path. I guess you misunderstand the modulo scheduling. If II is 1, the latency of mapping is not necessarily 1. For example, it takes two cycles for routing from MUL0 to LOAD2 and LOAD3. But the mapping can still start a loop iteration every cycle, which means II is 1. Of course, it will cause long latency to finish one iteration.
BTW, LISA uses the basic mapping module with ILP and SA from cgra-me, e.g, the routing algorithm.

**Comment by XYXhong** [comment]
what should I do to dump the routing path.

**Comment by zhaoying-LI** [comment]
I have not used the tool for a quite while. Please figure it out by yourself.

**Comment by XYXhong** [comment]
Okay, thank you for your answer.
